name: Continuous Integration

on:
  push:
    branches:
      - '*'
      - 'chore/covering-tests'

jobs:
  ci:
    name: Build, Test, Lint, and SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check for .mdc files in .cursor/rules
        run: |
          if ! ls .cursor/rules/*.mdc 1> /dev/null 2>&1; then
            echo "❌ No .mdc files found in .cursor/rules. This might indicate AI-generated output without code rules."
            exit 1
          else
            echo "✅ .mdc files found in .cursor/rules."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Check commit message
        id: check_commit
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if echo "$commit_message" | grep -iE "\[skip[ -]tests?\]" > /dev/null; then
            echo "skip_tests=true" >> $GITHUB_OUTPUT
          else
            echo "skip_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Tests
        if: steps.check_commit.outputs.skip_tests != 'true'
        continue-on-error: true
        run: npm test -- --coverage

      - name: Run Linter
        run: npm run lint

      - name: Run SonarQube analysis
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=INVENTUM-FE \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src \
            -Dsonar.tests=__tests__ \
            -Dsonar.test.inclusions=__tests__/**/*.test.tsx \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.coverageReportPaths=coverage/lcov.info \
            -Dsonar.coverage.exclusions=**/*.test.tsx
